stages:
  prepare_data:
    cmd: PYTHONPATH=src python -m air_quality_imputer.pipeline.prepare_data --params configs/pipeline/params.yaml
    deps:
      - src/air_quality_imputer/pipeline/prepare_data.py
      - src/air_quality_imputer/pipeline/common.py
      - src/air_quality_imputer/pipeline/dataset_adapters.py
      - src/air_quality_imputer/data/electricity_dataset.py
      - src/air_quality_imputer/training/data_utils.py
      - configs/pipeline/params.yaml
      - data/raw
    params:
      - configs/pipeline/params.yaml:
          - experiment
          - dataset
          - training.shared_validation_mask
          - paths.data_dir
          - paths.processed_dir
          - paths.scalers_dir
    outs:
      - data/processed/splits
      - data/processed/scalers

  train_models:
    cmd: PYTHONPATH=src python -m air_quality_imputer.pipeline.train_models --params configs/pipeline/params.yaml
    deps:
      - src/air_quality_imputer/pipeline/train_models.py
      - src/air_quality_imputer/pipeline/common.py
      - src/air_quality_imputer/tracking/mlflow_utils.py
      - src/air_quality_imputer/training/model_registry.py
      - src/air_quality_imputer/models
      - configs/pipeline/params.yaml
      - data/processed/splits
      - data/processed/scalers
    params:
      - configs/pipeline/params.yaml:
          - experiment.models
          - experiment.seed
          - training
          - models
          - paths.models_dir
          - tracking
    outs:
      - artifacts/models

  evaluate_models:
    cmd: PYTHONPATH=src python -m air_quality_imputer.pipeline.evaluate_models --params configs/pipeline/params.yaml
    deps:
      - src/air_quality_imputer/pipeline/evaluate_models.py
      - src/air_quality_imputer/pipeline/common.py
      - src/air_quality_imputer/tracking/mlflow_utils.py
      - src/air_quality_imputer/training/data_utils.py
      - src/air_quality_imputer/training/model_registry.py
      - src/air_quality_imputer/models
      - configs/pipeline/params.yaml
      - data/processed/splits
      - artifacts/models
    params:
      - configs/pipeline/params.yaml:
          - experiment
          - evaluation
          - models
          - paths.reports_dir
          - paths.plots_dir
          - paths.metrics_dir
          - tracking
    outs:
      - reports/model_eval
      - reports/plots/model_eval
    metrics:
      - reports/metrics/model_eval_metrics.json
    plots:
      - reports/metrics/summary_by_feature_for_dvc_plots.csv
