defaults:
  - model: classic_transformer
  - _self_

paths:
  data_dir: data/raw
  models_dir: artifacts/models
  processed_dir: data/processed/splits
  scalers_dir: data/processed/scalers

experiment:
  stations: [all_stations]
  models: [classic_transformer, saits]
  features: [PM10,PM2.5,temperature,rain,pressure,precipitation,wind_speed,clouds,wind_direction]
  never_mask_features: []
  block_size: 24
  step_size: 1
  missing_rate: 0.20
  seed: 42
  mask_mode: block_feature
  block_min_len: ${model.params.train_block_min_len}
  block_max_len: ${model.params.train_block_max_len}
  block_missing_prob: ${model.params.train_block_missing_prob}
  feature_block_prob: ${model.params.train_feature_block_prob}
  block_no_overlap: ${model.params.train_block_no_overlap}

training:
  epochs: 100
  batch_size: 256
  lr: 0.001
  patience: 250

hydra:
  run:
    dir: .
  output_subdir: null
